### ISSUE TITLE
getScanResults old level always returns 0

### ISSUE THREAD

**Issue by Tiwenty** [parsonsmatt/WifiWizard#17]
Hello again! With your update on the level value for the getScanResults method, it seems that the old level value always returns "0". Here is my code:

```javascript
WifiWizard.getScanResults({numLevels:1}, function(result){
    alert(result);
    showScanned(parseScan(result));
});
```

The alert() show me this: 
> [{"level":0,"SSID":"fenelonsio","BSSID":"58:8d:09:e2:ad:ad"},{"level":0,"SSID":"OKLM","BSSID":"a2:80:f5:41:3f:0d"}]

Is it a bug in the plugin or did I do something wrong? Thanks!

**Comment by parsonsmatt** [comment]
An integer value for the level will return an integer between 0 and n-1. If
you want the old behavior, you can pass true or 5. Let me know if that
works for you.

**Comment by Tiwenty** [comment]
Well it works, I thought giving 1 would be true. Thanks a lot!

**Comment by Sokarion** [comment]
For me it isn't ok, when i add an option WifiWizard.getScanResults({numLevels:5},...
I've no result.

**Comment by hoerresb** [comment]
Try using true instead of 5. E.g.  WifiWizard.getScanResults({numLevels:true},...

**Comment by parsonsmatt** [comment]
[The relevant code is here](https://github.com/parsonsmatt/WifiWizard/blob/edffcee0c0683cff5f943716cc60fd00108d1d8a/www/WifiWizard.js#L198-L211). The error message should definitely be updated. You would be seeing that error if neither the first nor second parameters to the `getScanResults` call were functions. Can you post the entire calling code that is getting you the error?
