### ISSUE TITLE
Unable to fetch wifiwizard plugin

### ISSUE THREAD

**Issue by lennycartier** [parsonsmatt/WifiWizard#18]
Hi Matt,

it seems that wifiwizard 0.2.8 cannot be teched at the moment : 

cordova plugin add com.pylonproducts.wifiwizard
Fetching plugin "com.pylonproducts.wifiwizard" via plugin registry
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.pylonproducts.wifiwizard/-/com.pylonproducts.wifiwizard-0.2.8.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.pylonproducts.wifiwizard/-/com.pylonproducts.wifiwizard-0.2.8.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.pylonproducts.wifiwizard/-/com.pylonproducts.wifiwizard-0.2.8.tgz
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

**Comment by parsonsmatt** [comment]
That's odd -- I just tried it and it worked. Are you able to successfully install any other plugins?

**Comment by lennycartier** [comment]
Sorry for the nois Matt, it seems related to cordova plugin repository issues : https://twitter.com/Ionicframework/status/573942398465667073
