### ISSUE TITLE
Submit latest version to https://build.phonegap.com/plugins

### ISSUE THREAD

**Issue by aksanoble** [parsonsmatt/WifiWizard#19]
Hi Matt, 

Thank you for a great plugin. I included it in my app and I used phonegap build to get the apk. The version included on build is old and lacks the latest api such as getScanResults. Do you think you can submit the latest version to https://build.phonegap.com/plugins  ? 

Thank you!

**Comment by parsonsmatt** [comment]
I'd submitted v0.2.8 after it was released, but Adobe never updated it or included it unfortunately.
