### ISSUE TITLE
Maintainership Transfer

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/WifiWizard#21]
I don't have the spare time to continue maintaining this plugin. If anyone wants to take over as the full-time maintainer, let me know and I can work on transferring the important stuff to you.

**Comment by andrewlamers** [comment]
Hey, we would be interested in taking maintainership of your plugin

**Comment by parsonsmatt** [comment]
Cool! Let me know the account you want added to the repository and I'll get it set up

**Comment by andrewlamers** [comment]
You can add this account,  and could you also add @hoerresb?

**Comment by parsonsmatt** [comment]
I've added the two accounts to the group. There's a rewrite that's decently underway in the `develop` branch that will be much easier to test, if you want to start working from that.
