### ISSUE TITLE
Getscanresult how retrieve result?

### ISSUE THREAD

**Issue by Danyzzz** [parsonsmatt/WifiWizard#22]
It is possibile an example? thanks!

**Comment by brugnara** [comment]
Do you mean retrieve wifi list? If so, here's an example:

```js
WifiWizard.listNetworks(function(wifisKnown) {
  console.log(wifisKnown);
});
```

**Comment by Danyzzz** [comment]
Is perfect, thanks a lot!

**Comment by Danyzzz** [comment]
I'm trying to connect to a new network and enter the WPA password but without success ... is possible to have another working code for this ?
I believe that the function to use are:

WifiWizard.formatWifiConfig(SSID, password, algorithm);
WifiWizard.formatWPAConfig(SSID, password);
WifiWizard.addNetwork(wifi, win, fail);
WifiWizard.connectNetwork(SSID, win, fail);

but how to use? Thanks a lot!

**Comment by parsonsmatt** [comment]
@Danyzzz , I'm going to go ahead and close this out as it was answered by another issue. Feel free to post again if you need assistance

**Comment by ghost** [comment]
> Remenber: you have to wait some seconds before read the scanResults because the phone takes some  In my app I'm used to perform a check every 2 seconds after the startScan for 10 seconds.

How you do that?
