### ISSUE TITLE
How to connect a new wifi network

### ISSUE THREAD

**Issue by Danyzzz** [parsonsmatt/WifiWizard#23]
I'm trying to connect to a new network and enter the WPA password but without success ... is possible to have a working code for this ?
I believe that the function to use are:

WifiWizard.formatWifiConfig(SSID, password, algorithm);
WifiWizard.formatWPAConfig(SSID, password);
WifiWizard.addNetwork(wifi, win, fail);
WifiWizard.connectNetwork(SSID, win, fail);

but how to use? Thanks a lot!

**Comment by parsonsmatt** [comment]
You'd run `var config = WifiWizard.formatWPAConfig("network name", "network password")`, then do `WifiWizard.addNetwork(config)`. If you're wanting to then connect, it's probably best to do that in the `win` method of the `addNetwork` function to ensure that it's running after it works. The full code might look like:

```javascript
var config = WifiWizard.formatWPAConfig("my network", "secret password");
WifiWizard.addNetwork(config, function() {
    WifiWizard.connectNetwork("my network");
});
```

Let me know how that works. If it doesn't work, post what parameters the win or fail functions receive.

**Comment by Danyzzz** [comment]
Thank you works perfectly!

**Comment by parsonsmatt** [comment]
You're welcome :D
