### ISSUE TITLE
Does this plugin work with android 5.0?

### ISSUE THREAD

**Issue by crapthings** [parsonsmatt/WifiWizard#25]
i've installed this plugin and try to use this method

    WifiWizard.getCurrentSSID(function(success){
         alert(success);
    }, function(error){
        alert(error);
    });

But nothing happened.

**Comment by parsonsmatt** [comment]
I don't have a 5.0 capable phone to test with, unfortunately. Does the fail callback do anything?

**Comment by crapthings** [comment]
Fail doesn't fire.

**Comment by crapthings** [comment]
I've got this error on console

    Uncaught ReferenceError: WifiWizard is not defined

lg g3 android 5.0

meteor.js  add this plugin

**Comment by Danyzzz** [comment]
I have a nexus on android 5.0, this code works perfectly in my device.

**Comment by crapthings** [comment]
after change plugin.xml

    <js-module src="www/WifiWizard.js" name="WifiWizard">
         	<clobbers target="window.WifiWizard"/>
     </js-module>

It works.

**Comment by hoerresb** [comment]
Going to merge this change to fix 'Uncaught ReferenceError: WifiWizard is not defined'. Thanks. 

Closing for now.
