### ISSUE TITLE
Does this plugin support iOS devices?

### ISSUE THREAD

**Issue by Santhosh25** [parsonsmatt/WifiWizard#28]
Does this plugin fully support iphone devices? 
I have installed and tested in iphone 5 its not working. Unable to get network list while device scanning.
Please advice if there is any solution.  Thanks in advance.

**Comment by parsonsmatt** [comment]
It doesn't. Apple's wifi manager doesn't allow applications to edit it like Android does, so many of the options aren't supported. From [the source](https://github.com/parsonsmatt/WifiWizard/blob/master/src/ios/NXWWifiWizard.m), it looks like only `fetchSSIDInfo` is supported.
