### ISSUE TITLE
Ios Scan Networks

### ISSUE THREAD

**Issue by zenmanenergy** [parsonsmatt/WifiWizard#29]
I just came across this IOS git project:  https://github.com/mongizaidi/LAN-Scan

Does that have the logic to get the startScan, scanNetwork and listNetworks methods working?

**Comment by Solido** [comment]
Thanks for sharing, I hope this will lead to an IOS scan inside WifiWizard :)

**Comment by hoerresb** [comment]
Thanks for sharing. I'm going to look into the project a bit more, but as far as I know there is no public IOS API that allows wifi scanning. 

There are private API's that do what you are looking for but use of private API's prevents an app from being distributed from the app store.

**Comment by Solido** [comment]
I wasn't aware of those limitations. Thank you @hoerresb for explaining them. BTW WifiWizard is the most advanced Cordova plugin in the wifi domain so we have some more expectations ;)

**Comment by hoerresb** [comment]
Closing for now, as there is no public IOS API that allows wifi scanning.
