### ISSUE TITLE
enable wifi hotspot

### ISSUE THREAD

**Issue by jaime-ez** [parsonsmatt/WifiWizard#30]
Hi, I'm wondering how to enable the wifi hotspot for a user that has my app installed. Can it be done with this plugin?
(I'm new to this)
Thanks

**Comment by crapthings** [comment]
@jaime-ez hey i think this plugin can't do that yet.

check this if you're on android device

https://github.com/floatinghotpot/cordova-plugin-wifi

it has enableWifiAP, but i haven't tried.

    enableWifiAP(istrue, params, okcallback, failcallback);

**Comment by parsonsmatt** [comment]
If the network ssid has been added, then you can connect with this
function:
https://github.com/parsonsmatt/WifiWizard/blob/master/README.md#wifiwizardconnectnetworkssid-win-fail

If the network hasn't been added, make a WifiConfig object and then use the
WifiWizard.addNetwork function with it

**Comment by jaime-ez** [comment]
Thanks!
I found this Java class https://github.com/nickrussler/Android-Wifi-Hotspot-Manager-Class that I might implement. 
But first I'll check your suggestion @crapthings !
