### ISSUE TITLE
WifiWizard.connectNetwork calls win callback even if wifi network is unavailable

### ISSUE THREAD

**Issue by untitledlt** [parsonsmatt/WifiWizard#31]
First thanks for a great plugin!
Here is my code:

```javascript
var onSuccessConnectToNetwork = function (result) {
    console.log(result);
};
var onFailConnectToNetwork = function (result) {
    console.log(result);
};
WifiWizard.connectNetwork('mySSID', onSuccessConnectToNetwork, onFailConnectToNetwork);
```
If I disable my wireless access point, provide wrong credentials, it still says `Network "mySSID" connected!`.
`onFailConnectToNetwork` gets called only if I disable wireless connection on my phone.
Is it possible to get actual connection result?

**Comment by hoerresb** [comment]
I would try to add the network first. For example, for WPA this is how I connect to the network. 

```javascript
                var wifi_network = WifiWizard.formatWifiConfig(ssid, 'password', 'WPA');
                WifiWizard.addNetwork(wifi_network, function (win) {
                    WifiWizard.connectNetwork(ssid, function (win) {
                        console.log(win);
                         // connection worked
                    }, function (fail) {
                       console.log(fail);
                       // connection failed.
                    });
                }, function (fail) {
                    console.log(fail);
                    // add network failed. 
                });
```

Also, please note this functionality is only available on android.

**Comment by untitledlt** [comment]
Thanks for answer!
Network is added and phone connects to network successfully after few seconds if credentials are ok and AP is available. The problem is that plugin calls `win` without waiting for actual connection establishment.
And yes, I am using Android on two of my phones.

**Comment by parsonsmatt** [comment]
Thanks for bringing this up! The Java code will return success whenever the network ID is found, and in fact only disables and reenables the network: [code here](https://github.com/parsonsmatt/WifiWizard/blob/master/src/android/src/com/pylonproducts/wifiwizard/WifiWizard.java#L265)

We'll probably want to include a loop in there which polls the current connection status, and returns true/false based on whether it actually connected.

**Comment by untitledlt** [comment]
I tried to implement this in Javascript with `getCurrentSSID` in loop, but it returns last used ssid even after disconnecting from network. How could I check the current connection status?

**Comment by fenwick67** [comment]
@parsonsmatt  maybe just add a javascript interface to `connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI)` so people can check the network status?

**Comment by jorisw** [comment]
+1 on this one.

I'm doing a `WifiWizard.addNetwork()` with a correct SSID but with an invalid passphrase.

A call to `WifiWizard.connectNetwork('mySSID',successCallback,errorCallback)` immediately fires the success callback, not giving me a chance to bring up a 'Invalid passphrase' message to the user. `errorCallback` is never fired.

**Comment by hoerresb** [comment]
We have a fix for this comming. I will push an update out soon since this has been a known issue for a while.

**Comment by jorisw** [comment]
Great.

**Comment by talpasco** [comment]
Any update on this? Still doesn't work...

**Comment by masoumiaa** [comment]
When I use a correct SSID and a **wrong Password**, It always call `successCallback` !
Any update on this ?

**Comment by sudhan-ionic** [comment]
hai @hoerresb 
  ```
var wifi_network = WifiWizard.formatWifiConfig(ssid, 'password', 'WPA');
                WifiWizard.addNetwork(wifi_network, function (win) {
                    WifiWizard.connectNetwork(ssid, function (win) {
                        console.log(win);
                         // connection worked
                    }, function (fail) {
                       console.log(fail);
                       // connection failed.
                    });
                }, function (fail) {
                    console.log(fail);
                    // add network failed. 
                });
```

var wifi_network = WifiWizard.formatWifiConfig(ssid, 'password', 'WPA');
instead of 'WPA' what must be replace in that place
WifiWizard documentation instead of `'WPA'` they using `algorithm`
can you pls help me

**Comment by ghost** [comment]
Still doesn't work... Is there any fix ?
