### ISSUE TITLE
More documentation about iOS

### ISSUE THREAD

**Issue by tacman** [parsonsmatt/WifiWizard#32]
"Currently, iOS only has limited functionality. Most functionality is only available on Android."

Can you spell out what does work on iOS?  Even if it just gets a list of network SSID's that would be useful for our purposes (though signal strength would be even better).

**Comment by hoerresb** [comment]
I believe the only functionality for iOS is to get the current ssid. There is no iOS public api that allows you to programmatically change wifi states or scan for a list of network SSID's. 

There are private API's that do what you are looking for but use of private API's prevents an app from being distributed from the app store.

**Comment by parsonsmatt** [comment]
Hi @tacman ! Sorry it took so long -- I've updated the README with more information about what is allowed. It's just `getCurrentSSID`.
