### ISSUE TITLE
Grab security protocol with .getScanResults

### ISSUE THREAD

**Issue by derek1906** [parsonsmatt/WifiWizard#36]
Is it possible for `.getScanResults` to include the used security protocol in the returned object? It would be nice if it can achieve this. An example returned object would be something similar to this:

    {
        BSSID: "...",
        SSID: "...",
        level: ...,
        algorithm: "WPA"
    }

**Comment by hoerresb** [comment]
This is definitely possible yes. In the scan results we can check the wifi
capabilities.

Referencing this post.
http://stackoverflow.com/questions/28905604/android-detecting-if-wifi-is-wep-wpa-wpa2-etc-programmatically

**Comment by hoerresb** [comment]
I've added the wifi capabilities to getScanResults. The results will look similar to this now

```javascript
{
     BSSID: "..."
     SSID: "..."
     capabilities: "[WPA-PSK-CCMP+TKIP][WPA2-PSK-CCMP+TKIP][ESS]"
     frequency: 2452
     level: 3
     timestamp: 21407208451
}
```

It will be very easy to parse out the results of the capabilities depending on the type you are looking for. Ex, 


```javascript
     if(results.capabilities.indexOf('WPA2') > -1){
         //WPA2
     }else if(results.capabilities.indexOf('WEP') > -1){
         //WEP
    } //etc.
```
