### ISSUE TITLE
Is the repo... dead?

### ISSUE THREAD

**Issue by bojidar-bg** [parsonsmatt/WifiWizard#37]
@parsonsmatt :+1: this repo is quite helpful for various project, but... it is dead/abandoned?

**Comment by parsonsmatt** [comment]
Essentially, yes. I made the plugin for a summer internship last year, and haven't worked with Android or Cordova since. I don't have an Android or Cordova setup to test pull requests, so I'm not able to confidently accept PRs.

If someone is interested in taking the project over, I'm happy to facilitate that.

**Comment by hoerresb** [comment]
I work with android and ionic / Cordova everyday.  I even use this plugin
in the application I'm working on. I feel comfortable updating the repo but
I've been very slow to do so.

I can go through some of the PRs this weekend and see what can be merged.

**Comment by derek1906** [comment]
@hoerresb If you are going to updating the repo (which is great!), are you going to implement #36?

**Comment by lepermunna** [comment]
+1 to that ;)

**Comment by hoerresb** [comment]
Sounds good. I will be sure to add that in.

**Comment by hoerresb** [comment]
.getScanResults is updated. It now returns all possible information of the scan results. Including frequency, time stamp and wifi capabilities. Here is an example of the json response. 

```javascript
{
     BSSID: "..."
     SSID: "..."
     capabilities: "[WPA-PSK-CCMP+TKIP][WPA2-PSK-CCMP+TKIP][ESS]"
     frequency: 2452
     level: 3
     timestamp: 21407208451
}
```

**Comment by JessePimenta** [comment]
@hoerresb if you have any example implementation you could share, would be greatly appreciated. trying to use methods similar to WifiManager's but just want to see a little more documentation on Wifiwizard. new to android/cordova

**Comment by lepermunna** [comment]
Hi Jesse,
I found this really helpful when getting started: https://github.com/parsonsmatt/WifiWizardDemo

**Comment by hoerresb** [comment]
@JessePimenta I would definitely take a look at the demo linked by @lepermunna https://github.com/parsonsmatt/WifiWizardDemo. 

Most functions are not that complected and can be taken from the read me. For example, this will return the current wifi ssid. 

```javascript
      WifiWizard.getCurrentSSID(function(response){
            //response is the current SSID
            console.log(response);
            },function(fail){
             //response if somethings should go wrong. 
             console.log(fail);
            });

```

If you have any other questions please let us know. Thanks.

**Comment by JessePimenta** [comment]
@hoerresb, @lepermunna  thanks a lot. 
now im running into issues when testing the app, it seems to have problems sourcing cordova.js from the folder it is in initially. also had to move the location of WifiWizard.js to get it to pick up the functions of wifiWizard. any idea why its not able to find the correct file path? just cloned it directly from the repo...
thanks again for your help

**Comment by JessePimenta** [comment]
@hoerresb @lepermunna I'm using Ionic and it cant seem to pick up WifiWizard. Maybe I'm not injecting it correctly...

**Comment by JessePimenta** [comment]
![screen shot 2015-09-09 at 12 24 50 pm](https://cloud.githubusercontent.com/assets/12524608/9771891/2db95652-56f6-11e5-8f63-9bd345a41f86.png)

**Comment by bojidar-bg** [comment]
@JessePimenta wait.... are you using it in the browser?

**Comment by JessePimenta** [comment]
tried in both browser and ionic simulator @bojidar-bg

**Comment by JessePimenta** [comment]
@bojidar-bg getting the same error in both

**Comment by hoerresb** [comment]
Ok. It's normal  for cordova.js not to be found when testing in your
browser. Also WifiWizard will be undefined if you only test this in your
browser.

To be tested properly deploy to your Android device.

**Comment by JessePimenta** [comment]
@hoerresb is there any way to test it in ionic without deploying to an android device?

**Comment by hoerresb** [comment]
I'm going to guess no. WifiWizard is using an Android API to do all the wifi confingurations. http://developer.android.com/reference/android/net/wifi/WifiManager.html

**Comment by hoerresb** [comment]
You might be able to use something like GenyMotion,  but I haven't tested it  yet. https://www.genymotion.com/#!/

**Comment by JessePimenta** [comment]
ah okay. thank you for your help, ill try it out

**Comment by hoerresb** [comment]
No problem. 

I think I will put up different demo using ionic and give some specific examples, but it won't be until the weekend.

**Comment by JessePimenta** [comment]
@hoerresb that would be awesome. looking forward to checking that out !
thank you again.
