### ISSUE TITLE
Released properly?

### ISSUE THREAD

**Issue by doganyazar** [parsonsmatt/WifiWizard#38]
In the README it is written that there is a release of v0.2.9. But I cannot access it. 
'cordova plugin add com.pylonproducts.wifiwizard'  gets v0.2.8 and hence no latest fixes.

**Comment by hoerresb** [comment]
Thanks for pointing this out. We will look into this.

In the meantime if you want the latest version you can use Cordova plugin
add https://github.com/parsonsmatt/WifiWizard

**Comment by lepermunna** [comment]
Note that the latest release of Cordova fails adding plugins from github directly if your project is mounted on a different drive than github. To get around this you can alternatively clone the github repo to your project directory and add the plugin from the cloned repo:

e.g.
git clone https://github.com/parsonsmatt/WifiWizard
cordova plugin add WifiWizard

**Comment by doganyazar** [comment]
Thanks guys.
I could not really find information about "cordova projects not hosted on github fail to add plugins from github". Can you please provide a link for it? Is it a bug? Or new behaviour?

I am using cordova with meteor and for now I am using the tarball version of the last commit :) 
cordova:com.pylonproducts.wifiwizard@https://github.com/parsonsmatt/WifiWizard/tarball/ca50357e60f36512e9036d3973a28a9acd896b36

**Comment by parsonsmatt** [comment]
I just pushed the plugin to the registries and it should be available now

@hoerresb , do you have a plugman account? I need to add you as an owner so you can push new versions too

**Comment by hoerresb** [comment]
@parsonsmatt. I have plugman setup. My username is hoerresb . Let me know if that works. Thanks.
