### ISSUE TITLE
Does the plugin be suit for ios?

### ISSUE THREAD

**Issue by shmilyliang** [parsonsmatt/WifiWizard#39]
Hi, does the plugin be suit for ios?
It seems that the plugin only for android.

**Comment by lepermunna** [comment]
Hi, unfortunately iOS is not supported, because there is no public API for controlling WiFi. See duplicate here [32](https://github.com/parsonsmatt/WifiWizard/issues/32)

**Comment by parsonsmatt** [comment]
iOS is supported in a limited manner. See the README for complete information.
