### ISSUE TITLE
Error calling addNetwork

### ISSUE THREAD

**Issue by atkulp** [parsonsmatt/WifiWizard#40]
I call formatWifiConfig to create the configuration, then addNetwork.  I get:

Uncaught TypeError: Object #<Object> has no method 'trim' in WifiWizard.js on line 76.

Is this a known problem?

**Comment by hoerresb** [comment]
Thanks for pointing this out. I have yet to run into this error. Are you passing the formatted config as an argument in addNetwork? Ex, 

```javascript
               var device_wifi = WifiWizard.formatWifiConfig('ssid', 'password', 'WPA');
                // pass in formatted config to addNework 
                WifiWizard.addNetwork(device_wifi, function (win) {
                   // add network succeeded. 
                }, function (fail) {
                  // add network failed
                });
```

**Comment by atkulp** [comment]
I figured it out.  I was passing the JSON config object to the
connectNetwork() call instead of just the ssid.  All good now!

**Comment by hoerresb** [comment]
Glad you figured it out. I'm going to make a note of this as we should probably check to make sure the argument being passed in is a string.
