### ISSUE TITLE
update npm

### ISSUE THREAD

**Issue by hoerresb** [parsonsmatt/WifiWizard#45]
Hey @parsonsmatt, I've been working on a few updates for the WifiWizard repo. Mostly small bugs that have been pointed out or are outstanding. It seems that cordova is moving the plugins to npm seen via http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html. 

It seems we have already taken care of this, but I was wondering if I could be added as a user. When I tried to update using npm publish ../pathToWifiWizard I was told I do not have permission to do so. 

Username is hoerresb

There's no rush on this. Thanks.

**Comment by parsonsmatt** [comment]
> We will be switching CPR to read-only on July 15th, 2015.

Lol that explains why I couldn't add anyone!

You're on the plugin now :)
