### ISSUE TITLE
Build failed with current master repo

### ISSUE THREAD

**Issue by jorisw** [parsonsmatt/WifiWizard#51]
Since `cordova plugin add com.pylonproducts.wifiwizard` pulled `0.2.9` instead of the new `0.2.10`, I decided to install using the Master `.git` URL. However this gives me a build error:

```
platforms/android/src/com/pylonproducts/wifiwizard/WifiWizard.java:275: error: package NetworkInfo does not exist
              NetworkInfo.DetailedState connectionState = info.getDetailedStateOf(info.getSupplicantState());
```

Building against Android target version 22.

**Comment by jorisw** [comment]
I was able to fix this build error by inserting the following at line 24 of `WifiWizard.java`:

`import android.net.NetworkInfo;`

However, it would appear that the current Master branch is missing the `#fix/api_v_16` fixes you made earlier. 'cause the scan result callback is no longer firing on my Android 4.1.

And a regular `cordova plugin add com.pylonproducts.wifiwizard`still installs `0.2.9` here.

**Comment by hoerresb** [comment]
yep, I just added that. If pull from master it should be fine now.

**Comment by jorisw** [comment]
Thanks, but the release still seems to be missing the `#fix/api_v_16` fix.
