### ISSUE TITLE
getCurrentSSID and getCurrentBSSID wrong in android

### ISSUE THREAD

**Issue by lianghuiyuan** [parsonsmatt/WifiWizard#58]
#### getCurrentSSID(function(successParam)(), function(errorParam));

In android platform: there are a double quotes more in successParam. I think it may be a bug.
![ed51be35-6d20-4911-bda3-0c790a5b1c99](https://cloud.githubusercontent.com/assets/8090998/11551221/5308e2d4-99b2-11e5-9984-d7029f6b6d16.png)

In IOS platform: It works fine.
![ade4effc-0970-451a-98f5-e0e86b288b87](https://cloud.githubusercontent.com/assets/8090998/11551230/66c4d698-99b2-11e5-83ea-7478ab963ea1.png)

**Comment by lianghuiyuan** [comment]
The problem fixed in #59.

**Comment by pfiaux** [comment]
Nice fix saddly https://github.com/hoerresb/WifiWizard/pull/59 never got merged so if you run into this problem you're better off using a fork.
