### ISSUE TITLE
Are all features supported in ios?

### ISSUE THREAD

**Issue by savanvadalia** [parsonsmatt/WifiWizard#64]
Hi 

My first project in mobile development, please forgive my ignorance for mobile development.

So far I have been using this plugin to connect a wifi device via an andriod phone.

I saw this below comment for the read me:
"iOS has limited functionality, as Apple's WifiManager equivalent is only available as a private API. Any app that used **these features would not be allowed on the app store**. The only function availabe for iOS is getCurrentSSID."

Does this mean at this stage I can't connect a wifi access point on ios using this plugin?
Are there any future plans to make this available?

Regards,
Savan

**Comment by lepermunna** [comment]
Hi Savan,
You are correct, you can't use this plugin to connect an iPhone to a Wi-Fi network. As far as I know there are no plans to add full support for iOS in the future as there is no public API access to the Wi-Fi service available in iOS. 
Cheers

**Comment by savanvadalia** [comment]
Thank you lepermunna

This helps me make a decision on how to keep my app flow based on ios and andriod.
