### ISSUE TITLE
isWifiEnabled and setWifiEnabled do not work for iOS

### ISSUE THREAD

**Issue by lentyaishe** [parsonsmatt/WifiWizard#69]
Hi,

Both isWifiEnabled and setWifiEnabled are not working for iOS. I also saw that in iOS native code the isWifiEnabled function implementation is empty and setWifiEnabled implementation always return "not supported".

Are you planning to implement both these functionalities for iOS?

Thanks in advance

**Comment by parsonsmatt** [comment]
This is my understanding of the situation:

> iOS has limited functionality, as Apple's WifiManager equivalent is only available as a private API. Any app that used these features would not be allowed on the app store. The only function availabe for iOS is getCurrentSSID.

There are no current plans to add the functions, as inclusion of that code would probably disqualify apps on the app store.

**Comment by lentyaishe** [comment]
Hi,

Thanks for your reply...
Don't know about accessibility of that application but this plugin: [Cordova diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) does have implementation for `isWifiEnabled()` for iOS.

Best regards
