### ISSUE TITLE
Wifi scan result issue in ios

### ISSUE THREAD

**Issue by MuraliKrishnaDev** [parsonsmatt/WifiWizard#70]
Hi,

I need to use wifi scan functionality in ios,

Is there any plugin or work around,

Please help regarding this,

Thanks and Regards,
Murali

**Comment by MuraliKrishnaDev** [comment]
Hi,

Waiting for your response,
Please help us regarding this,

Best Regards,
Murali

**Comment by parsonsmatt** [comment]
duplicate #72
