### ISSUE TITLE
WifiScanresult works for iOS device?

### ISSUE THREAD

**Issue by MuraliKrishnaDev** [parsonsmatt/WifiWizard#72]
Hi,

WifiScanresult functionality will not work on iOS device,
Please guide me is there Any plugin or workaround to get scanresult in iOS devices,

Thanks and Regards,
Murali

**Comment by parsonsmatt** [comment]
Hi Murali,

iOS is not fully supported. See:

> iOS has limited functionality, as Apple's WifiManager equivalent is only available as a private API. Any app that used these features would not be allowed on the app store. The only function availabe for iOS is getCurrentSSID.

Thanks!
